# CC / CLFAGS 는 추후 쓰일 일이 있을 것 같아 작성
#CC = gcc
#CFLAGS = -Wall -Wextra - Werror

AR = AR
ARFLAGS = -rc

TARGET = libft.a

SRCS = first.c second.c third.c
OBJS = first.o second.o third.o

$(TARGET) : $(OBJS)
	$(AR) $(ARFLAGS) $(TARGET) $(OBJS) 